### ISSUE TITLE
Create "wizard" that creates transfer entries

### ISSUE THREAD

**Issue by jdenoc** [jdenoc/money-tracker#159]
A _wizard_ (modal) should be created that allows a user to enter information for a transfer transaction once and subsequently creates two (2) entries. One for each relevant account with a `transfer` tag.

**Comment by jdenoc** [comment]
**New table needed.**
```
table: `entry_transfers`
|name   |type     |attributes             |default          |
+-------+---------+-----------------------+-----------------|
|id     |INT(11)  |UNSIGNED AUTO_INCREMENT|NOT NULL         |
|from_id|INT(11)  |UNSIGNED               |NULL             |
|to_id  |INT(11)  |UNSIGNED               |NULL             |
|stamp  |TIMESTAMP|                       |CURRENT_TIMESTAMP|
```

**Comment by jdenoc** [comment]
**TODO**
- [ ] Database migration to remove tags labeled "_transfer_" that might exist.
- [ ] Database migration to create new `entry_transfers` table.
- [ ] Button in navbar to open a _transfer_ modal.
- [ ] New _transfer_ modal. Should be similar to entries modal.
- [ ] New column in the list entries table to show that an entry is part of a transfer.
  - See https://fontawesome.com/icons/exchange-alt?style=solid for example icon for header.
- [ ] `GET /api/entries` needs to be updated so that `is_transfer` is present in output.
- [ ] New _filter by "transfer"_ option in the _filter_ modal.

**Comment by jdenoc** [comment]
_Insert_ flow for the transfer modal when saved.
```
          [transfer modal data]
                    |
  +-----------------+-----------------+
  |                 |                 |
`entries`         `entries`         `entry_transfers`
 (from)            (to)              (after IDs from "from" and "to" are retrieved)
 -id               -id               -id
 -entry_date       -entry_date       -from_id (from entry)
 -entry_value      -entry_value      -to_id (to entry)
 -account_type_id  -account_type_id  -stamp
 -memo             -memo
 -expense=1        -expense=0
 -tags             -tags
 -attachments      -attachments
 -create_stamp     -create_stamp
```

**Comment by jdenoc** [comment]
Transfer modal attributes
- Date
- Value
- From
- To
- Memo
- Tags
- Attachments

**Comment by jdenoc** [comment]
Due to UI refresh (#28), this issue will be tackled after that.
