### ISSUE TITLE
Upgrade UI to use VueJS

### ISSUE THREAD

**Issue by jdenoc** [jdenoc/money-tracker#28]
[Vue JS](https://vuejs.org), plus this upgrade will also include using [bulma](https://bulma.io) for styling instead of bootstrap.

This upgrade will require utilising [NodeJS](https://nodejs.org/en/) and ~[NPM](https://www.npmjs.com)~ [Yarn](https://yarnpkg.com/en/).

**EDIT:** _See [here](https://github.com/jdenoc/money-tracker/issues/28#issuecomment-365214969) for list of ongoing tasks related to this._

**EDIT2:** Bringing this up from further down the conversation.
Vue components we expect to use:
- [x] institutions pane
  - [x] institutions row
  - [x] account row
  - [x] closed account row
- [x] entries list
- [x] entry list row
- [x] loading dialog/screen
- [x] entry modal
  - [x] Hotkey to close entry modal (See #151)
  - [x] Order attachment elements within entry-modal (See #170)
- [x] filter modal
  - [x] Allow filtering of entries by _disabled_ `account`/`account-type` (See #173)
- [x] transfer modal (See #159)
- [x] statistics/summary page (See #94)
- [x] settings page (See #96)
  - [x] institution/account/account-type/tag update section (See #95)

**Comment by jdenoc** [comment]
**Suggestion:** Use [Epic Spinners](http://epic-spinners.epicmax.co/#/)

**Comment by jdenoc** [comment]
[VueJS/Laravel integration tutorials](https://laracasts.com/series/learn-vue-2-step-by-step)

**Comment by jdenoc** [comment]
[Testing Vue tutorials](https://laracasts.com/series/testing-vue)

**Comment by jdenoc** [comment]
[Upload file(s)](https://serversideup.net/uploading-files-vuejs-axios/?utm_source=mybridge&utm_medium=blog&utm_campaign=read_more)

**Comment by jdenoc** [comment]
[write unit tests for VueJS](https://scotch.io/tutorials/how-to-write-a-unit-test-for-vuejs)

**Comment by jdenoc** [comment]
**Suggestion:** Use [CSS glitch effect](https://tympanus.net/codrops/2017/12/21/css-glitch-effect/)

**Comment by jdenoc** [comment]
[Vuex state](https://sabe.io/tutorials/getting-started-with-vuex)

**Comment by jdenoc** [comment]
Removal/replacement of `Bower`. See #76

**Comment by jdenoc** [comment]
[Building a Vue SPA with Laravel](https://laravel-news.com/using-vue-router-laravel)

**Comment by jdenoc** [comment]
Vue components we expect to use:
- [ ] entry list row
- [ ] entry modal
- [ ] filter modal
- [ ] institutions pane
- [ ] institutions row
- [ ] account row
- [ ] closed account row
- [ ] entries list

**Comment by jdenoc** [comment]
User profile image tool: https://laravelexamples.com/tag/laravolt-avatar
