### ISSUE TITLE
installation script

### ISSUE THREAD

**Issue by jdenoc** [jdenoc/money-tracker#336]
Create an installation script.
It should do everything listed in https://github.com/jdenoc/money-tracker/blob/master/README.md#installation

# TODO:

### SYSTEM
- [ ] php installed
  - [ ] minimum php version
- [ ] node installed
  - [ ] minimum node version
- [ ] composer installed
- [ ] database installed on system (mysql)

### DOWNLOAD
- [ ] git installed OR perform a wget/curl call
  - [ ] git checkout
  - [ ] record latest version acquired
- [ ] `composer install --no-dev`(dev)  _OR_  `composer install` (prod)
- [ ] `yarn install` _OR_ `npm install`

### INIT
- [ ] `cp .env.example .env`
  - [ ] prompt for variable values
- [ ] `artisan key:generate`
- [ ] `artisan app:version {checked out version}`
- [ ] `artisan migrate`
- [ ] `yarn run build-dev` _OR_ `yarn run build-prod`

### OPTIONAL
- [ ] `--dev` _OR_ `--prod` flag/option
- [ ] `composer run-script ide-helper` (for dev)
- [ ] `--cache` _OR_ `--optimise` flag/option
  - [ ] `artisan config:cache`
  - [ ] `artisan view:cache`

**Comment by jdenoc** [comment]
May be of use...
https://laravel-news.com/laravel-console-wizard
