### ISSUE TITLE
Construct an example docker-compose.prod.yml

### ISSUE THREAD

**Issue by jdenoc** [jdenoc/money-tracker#550]
Should include:

- [ ] application docker container
  - [ ] image: github container registry link; see [here](https://github.com/jdenoc/money-tracker/issues/547)
  - [ ] ports: `TBD:80`
  - [ ] volumes: `TBD:/var/logs`, `TBD:/var/www/money-tracker/storage/app/attachments`, `TBD:/var/www/money-tracker/storage/app/tmp-uploads`, `TBD:/var/www/money-tracker/database/snapshots`
  - [ ] env_file: `.env.application`
  - [ ] depends_on: `database`, `cache`, _healthy states_
  - [ ] networks: `net.money-tracker`
- [ ] mysql docker contianer
  - [ ] image: github container registry link; see [here](https://github.com/jdenoc/money-tracker/issues/547)
  - [ ] volumes: `TBD:/var/log/mysql`, `db.money-tracker:/var/lib/mysql
  - [ ] env_file: `.env.mysql`
  - [ ] networks: `net.money-tracker`
- [ ] memcached docker container
  - [ ] image: github container registry link; see [here](https://github.com/jdenoc/money-tracker/issues/547)
  - [ ] volumes: `cache.money-tracker:{cache directory}`, `TBD:{logs directory}`
  - [ ] env_file: `.env.cache`
  - [ ] networks: `net.money-tracker`
- [ ] volumes: `db.money-tracker`, `cache.money-tracker`
- [ ] networks: `net.money-tracker`
- [ ] secrets
  - https://docs.docker.com/compose/use-secrets/
